Feature/set mongodb
codex-team/manager-ai pull request #10
Opened 2019-10-28 21:55 UTC by SunnyCapt

2019-10-29 15:03 UTC, n0str requested changes

2019-10-29 15:03 UTC, n0str commented on docker-compose.yml
> +    image: mvertes/alpine-mongo:4.0.6-1
что за нестандартный образ монги?  Давай лучше `mongo:4.2`

2019-10-29 15:03 UTC, SunnyCapt commented on docker-compose.yml
> +    image: mvertes/alpine-mongo:4.0.6-1
окей, просто этот в два раза меньше дефолтного

2019-10-30 19:21 UTC, n0str approved these changes

2019-10-31 05:07 UTC, neSpecc approved these changes

2019-10-31 17:41 UTC, merged