refactoring && start impl controller
codex-team/manager-ai pull request #11
Opened 2019-11-01 04:14 UTC by SunnyCapt

2019-11-03 23:55 UTC, n0str approved these changes

2019-11-04 14:56 UTC, nikmel2803 requested changes
+ 91 строка -- нет в коде класса Service

описать аргументы методов

2019-11-04 14:56 UTC, nikmel2803 commented on tasks.py
> +from yaml import load
нету в зависимостях

2019-11-04 14:56 UTC, nikmel2803 commented on tasks.py
> +        self.__dict__.update(kwargs)
а для чего это надо?
какие-то неявные операции
Не помешало бы  написать коммент

2019-11-04 14:56 UTC, nikmel2803 commented on tasks.py
> +        return
None != List[Tuple[TaskWrapper, Dict["cron fields"]]]

2019-11-04 14:56 UTC, nikmel2803 commented on tasks.py
> +    def deserialize(cls, kwargs: Dict[str, list or str or int or "etc"]):
`kwargs: Dict[str, list or str or int or "etc"]`
что означает etc? IDE ругается на это слово
И вообще что подразумевается под этим аргументом?

2019-11-04 16:54 UTC, SunnyCapt commented on tasks.py
> +from yaml import load
так вот же оно ![изображение](https://user-images.githubusercontent.com/42912268/68140260-92f28a00-ff3c-11e9-8140-ae87af396e6c.png)

2019-11-05 07:17 UTC, SunnyCapt commented on tasks.py
> +from yaml import load
так вот же оно ![изображение](https://user-images.githubusercontent.com/42912268/68140260-92f28a00-ff3c-11e9-8140-ae87af396e6c.png)

2019-11-05 10:22 UTC, nikmel2803 commented on tasks.py
> +from yaml import load
Да, ты прав, у меня что-то IDE не подхватила их

2019-11-05 12:46 UTC, nikmel2803 approved these changes

2019-11-05 12:57 UTC, merged