BaseTask class
codex-team/manager-ai pull request #14
Opened 2019-11-11 02:46 UTC by SunnyCapt

* write BaseTask class
* fix
* refactoring

2019-11-16 10:36 UTC, nikmel2803 requested changes

2019-11-16 10:36 UTC, nikmel2803 commented on src/controller.py
> +def task_handler(serialized_task: dict):
мы наоборот все функции по классам пихали
зачем это тут?

2019-11-16 10:36 UTC, nikmel2803 commented on src/controller.py
> +    _notifiers = SRC_NOTIFIERS
надо описать поле

2019-11-16 10:36 UTC, nikmel2803 commented on src/settings.py
> +# PROXY = {
давай удалим то, что вообще не используется. Эти настройки, например

2019-11-16 10:36 UTC, nikmel2803 commented on tests/tasks/hello_world.py
> +import unittest
название теста неправильное

2019-11-16 16:43 UTC, n0str commented on config.sample.yml
> +
Лишний пробел

2019-11-16 16:43 UTC, n0str commented on src/controller.py
> +            logger.error(f"Notifiers is wrongs")
Не понял этого сообщения.
`Notifier is wrong`? или `Notifiers are wrong`?

2019-11-20 00:54 UTC, SunnyCapt commented on src/controller.py
> +            logger.error(f"Notifiers is wrongs")
`Notifiers are wrong`

2019-11-20 00:57 UTC, SunnyCapt commented on src/controller.py
> +def task_handler(serialized_task: dict):
Ивану: мне казалось что для шедулера нужна функциия как таковая, вне класса. Скорее всего я ошибся(спутал с селери) и `task_handler` можно засунуть обратно в класс, как и было

2019-11-20 01:13 UTC, SunnyCapt commented
О чем реквест: добавил абстрактный класс-обертку для тасков, порефакторил, дополнил код необходимыми методами/функциями, написал пример реализованного таска(HelloWorldTask) и тесты к нему(из последних двух составляющих должна стать понятна идея).

Инфа о том какой класс надо заюзать в качестве обертки n-ого таска указана в конфиге самого таска в поле (на данный момент) scenario(например если указано `hello_world`, будет искаться класс `HelloWorldTask`).

**Что тут делать Ивану**: проверить все ли работает(после моих изменений контроллера и прочего). Разложить Классы тасков из src/tasks.py по отдельным модулям(`src/tasks/base.py`, `src/tasks/helloworld.py`) и соответственным образом переписать `_get_task_class`/`_create_task_class_name`

**Чуть детальнее**: позапускать все существующие тесты, проверить работает ли контроллер (может ли выполнить хоть какую нибудь задачу по крону), проверить методы и прочее, все что подверглось изменениям в рамках этого реквеста. 

В идеале бы написать тесты под контроллер, но если это не горит то можно оставить на меня.

2019-11-26 09:23 UTC, n0str commented on src/controller.py
> +from copy import deepcopy
docker-compose.yml соответствует новой структуре?

2019-11-26 14:31 UTC, nikmel2803 approved these changes

2019-11-26 14:33 UTC, n0str approved these changes

2019-11-26 14:35 UTC, merged