Add running scenarios
codex-team/manager-ai pull request #16
Opened 2019-11-19 17:35 UTC by tanabahh

2019-11-19 18:17 UTC, n0str commented on src/scenarios/xpath.py
> +            self.url = kwargs["xpath"]["url"]
если kwargs определены, почему бы их не перечислить явно?

2019-11-19 18:17 UTC, n0str commented on src/scenarios/xpath.py
>          self.timestamp_id: str = self.__get_hash(self.url + self.xpath)
по сигнатуре __get_hash должно быть понятно, что это str

2019-11-19 18:17 UTC, n0str commented on src/scenarios/xpath.py
> +export = XPathScenario
это что такое? Какой-то nodejs. надо поресерчить паттерн ли это. Выглядит коряво.

2019-11-19 18:17 UTC, n0str commented on src/taskscontroller.py
> +            scenario = import_module("src.scenarios."+src["scenario"])
Лучше сделать через format string

2019-11-19 18:17 UTC, n0str commented on src/taskscontroller.py
> +            task = scenario.export
надо поресерчить паттерн ли это. Выглядит коряво.

2019-11-26 16:49 UTC, nikmel2803 reviewed
мда, надо было линукс ставить

2019-11-26 16:49 UTC, nikmel2803 commented on src/tasks/xpath.py
>          :param params: A dictionary with initial parameters for XPathScenario
доки устарели

2019-11-26 16:49 UTC, nikmel2803 commented on src/tasks/xpath.py
>      A class representing a scenario in which you need to get an html element by xpath
добавь сюда плз пример конфига yml, который ты мне кидала

2019-11-26 16:49 UTC, nikmel2803 commented on src/tasks/xpath.py
> +        self.timestamp_id: str = self.__get_hash(self.xpath['url'] + self.xpath['xpath'])
по идее timestamp_id должен при сериализации теряться

2019-11-26 21:51 UTC, n0str requested changes

2019-11-26 21:51 UTC, n0str commented on src/tasks/xpath.py
> +        BaseTask.__init__(self, name, schedule, transport, scenario, **kwargs)
Можно использовать super().__init__

2019-11-26 21:51 UTC, n0str commented on src/tasks/xpath.py
> +        self.timestamp_id: str = self.__get_hash(self.xpath['url'] + self.xpath['xpath'])
Мне не нравится название. timestamp - это про время. Предлагаю task_id

2019-11-26 21:51 UTC, n0str commented on src/tasks/xpath.py
> +            elem_lst = tree.xpath(self.xpath["xpath"])
Путаное название. Нужно в конфиге придумать что-то отличающееся, чтобы xpath не лежал внутри xpath.
Какой-нибудь config или params вполне подойдет.

2019-11-27 19:37 UTC, n0str approved these changes

2019-11-28 08:57 UTC, nikmel2803 approved these changes

2019-11-28 09:28 UTC, merged