telegram transport
codex-team/manager-ai pull request #6
Opened 2019-10-17 13:56 UTC by tanabahh

2019-10-17 13:57 UTC, n0str commented on transport_telegram.py
> +    requests.post(webhook, data={message.encode('cp1251')})
Почему cp1251? Дефолтная кодировка utf8

2019-10-17 13:58 UTC, n0str requested changes

2019-10-17 13:58 UTC, n0str commented on transport_telegram.py
> +    requests.post(webhook, data={message.encode('cp1251')})
Нет обработки ошибок

2019-10-17 13:58 UTC, n0str commented on transport_telegram.py
> +import requests
Давай добавим пару тестов? Unittests в папке tests?

2019-10-18 19:27 UTC, n0str requested changes

2019-10-18 19:27 UTC, n0str commented on tests/transport_test.py
> +            ok = request.body == b"message=Test+telegram+transport"
Прочитай пожалуйста доки. Возможно там есть паттерны использования.
https://httpretty.readthedocs.io/en/latest/
Как минимум там вижу параметр parsed_body.

2019-10-18 19:27 UTC, n0str commented on tests/transport_test.py
> +        response = requests.post('http://transport_test.com/', data={"message": "Test telegram transport"})
Зачем этот post? по задумке post делает твоя функция

2019-10-18 19:27 UTC, n0str commented on transport_telegram.py
> +    except ValueError:
Почему только ValueError? А ошибки таймаута?

2019-10-18 19:27 UTC, n0str commented on transport_telegram.py
> +def transport_telegram(message, webhook):
Нужно добавить сюда настройки таймаута (пока можешь их захардкодить, потом будем из конфига глобального получать.

2019-10-19 08:57 UTC, tanabahh commented on tests/transport_test.py
> +        response = requests.post('http://transport_test.com/', data={"message": "Test telegram transport"})
Угу, тут ошибка. Проблема в том что он почему-то выводить кучу ошибок на response = requests.get("http://transport_test.com/")
Мне же нужно проверить что туда пришло, для этого беру get, и все ломается
Сейчас пытаюсь разобраться с этим

2019-10-19 09:48 UTC, tanabahh commented on transport_telegram.py
> +def transport_telegram(message, webhook):
> Нужно добавить сюда настройки таймаута (пока можешь их захардкодить, потом будем из конфига глобального получать.

А если возникла ошибка таймаута или ConnectionError, нужно пробовать повторное подключение, или просто выбрасывать ошибку

2019-10-19 09:48 UTC, tanabahh commented on tests/transport_test.py
> +        response = requests.post('http://transport_test.com/', data={"message": "Test telegram transport"})
> Зачем этот post? по задумке post делает твоя функция

Угу, тут ошибка. Проблема в том что он почему-то выводить кучу ошибок на response = requests.get("http://transport_test.com/")
Мне же нужно проверить что туда пришло, для этого беру get, и все ломается
Сейчас пытаюсь разобраться с этим

2019-10-21 07:41 UTC, n0str requested changes
Чуток дожать

2019-10-21 07:41 UTC, n0str commented on transport_telegram.py
> +def transport_telegram(message, webhook):
Посмотри какие есть практики обычные в такой ситуации? Предлагаю сделать 3 попытки подключения и выкидывать ошибку.
Только используй пожалуйста стандартный функционал библиотеки requests (https://dev.to/ssbozy/python-requests-with-retries-4p03) или что-то подобное.

2019-10-21 07:41 UTC, n0str commented on transport_telegram.py
> +    flag = 0
Это что-то странное. Достаточно прокинуть дальше https://docs.python.org/3/tutorial/errors.html
```
import sys

try:
    f = open('myfile.txt')
    s = f.readline()
    i = int(s.strip())
except OSError as err:
    print("OS error: {0}".format(err))
except ValueError:
    print("Could not convert data to an integer.")
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise
```

2019-10-21 07:41 UTC, n0str commented on transport_telegram.py
> +            print('Wrong webhook')
Вместо print, нужно использовать logging. https://docs.python.org/3/library/logging.html

2019-10-21 07:41 UTC, n0str commented on transport_telegram.py
> +            time.sleep(1)
sleep встроен в стандартный функционал retry, о котором я говорил

2019-10-23 17:00 UTC, n0str approved these changes

2019-10-23 18:14 UTC, nikmel2803 approved these changes

2019-10-23 18:15 UTC, merged