Feature/xpath strategy
codex-team/manager-ai pull request #7
Opened 2019-10-17 22:15 UTC by carpet-knight

2019-10-18 10:55 UTC, n0str commented on tests/scenarios_tests/xpathscenario_test.py
> +params_list = [
Тесты нужно оформить в стиле unittests.

Статья: https://pythonworld.ru/moduli/modul-unittest.html
Ещё я на коленке пример накидал: https://gist.github.com/n0str/c6682e8abc16b969b183b681c343bdb1

2019-10-18 12:47 UTC, neSpecc requested changes

2019-10-18 12:47 UTC, neSpecc commented on scenarios/xpathscenario.py
> +class XPathScenario:
надо описать предназначение и суть класса.

2019-10-18 12:47 UTC, neSpecc commented on scenarios/xpathscenario.py
> +        self.url = params['url']
свойства класса не задокументированы

2019-10-18 12:47 UTC, neSpecc commented on scenarios/xpathscenario.py
> +    def __write_json(self, timestamps_dict):
параметры не задокументированы

2019-10-23 00:02 UTC, germanganys commented on scenarios/xpathscenario.py
> +        self.url = params['url']
**params можно как kwargs поставить еще

2019-10-23 00:02 UTC, germanganys commented on scenarios/xpathscenario.py
> +        self.url = params['url']
**params можно как kwargs поставить еще

2019-11-04 15:10 UTC, nikmel2803 commented on tasks.py
>      """Set of class/static methods for various purposes"""
этого файла не должно быть в диффах твоего реквеста. Удали плз

2019-11-04 15:10 UTC, nikmel2803 commented on scenarios/xpathscenario.py
> +    # def checkout_timestamp(self, element_info: dict):
если не нужно, то надо удалить

2019-11-04 15:10 UTC, nikmel2803 commented on scenarios/xpathscenario.py
> +        except Exception:
```suggestion
        except:
```

2019-11-06 15:03 UTC, n0str approved these changes

2019-11-07 18:51 UTC, neSpecc approved these changes

2019-11-08 13:11 UTC, merged