Feature/scheduled task launch
codex-team/manager-ai pull request #8
Opened 2019-10-17 22:28 UTC by SunnyCapt

2019-10-18 10:15 UTC, neSpecc requested changes

2019-10-18 10:15 UTC, neSpecc commented on README.md
> + 1) create config/local_settings.py file and set the necessary configs in it
`necessary configs` это какие? может добавить .sample ?

2019-10-18 10:15 UTC, neSpecc commented on README.md
> +        # xpath expression for watсhing element
лучше отделять пары коммент+ключ пустыми строками, а то сейчас каша

2019-10-18 10:15 UTC, neSpecc commented on README.md
> +    tasks:
Это надо завернуть в блок yml-кода

2019-10-18 10:15 UTC, neSpecc commented on README.md
> +    tasks:
в смысле в маркдауне

2019-10-18 10:15 UTC, neSpecc commented on tasks.py
> +    """Task processing"""
что входит в понятие processing?

2019-10-18 10:15 UTC, neSpecc commented on tasks.py
> +        serialized_task = Service.serialize_task(task)
нет доков

2019-10-23 06:04 UTC, n0str commented on docker-compose.yml
> +    container_name: m-ai
Зачем container_name? Пусть лучше называются со стандартными префиксами

2019-10-23 06:04 UTC, n0str commented on docker-compose.yml
> +  tmp:tmp
tmp:tmp? Звучит как-то не продакшн-реди.

2019-10-23 17:22 UTC, n0str approved these changes

2019-10-23 17:22 UTC, n0str commented on Dockerfile
> +RUN pip install -r requirements.txt
Давай команду по запуску сервера сюда внесём как entrypoint

2019-10-23 18:22 UTC, neSpecc requested changes
нужно создать файл-сэмпл конфига

2019-10-23 18:43 UTC, neSpecc approved these changes

2019-10-24 13:36 UTC, merged