Message creator
codex-team/manager-ai pull request #9
Opened 2019-10-19 07:14 UTC by germanganys

2019-10-19 14:16 UTC, n0str requested changes

2019-10-19 14:16 UTC, n0str commented on message_creator.py
> +# Test driver
Тест нужно вынести в отдельный файл `tests/message_creator_test.py` и оформить с соответствии с unittests: https://docs.python.org/3/library/unittest.html#basic-example

2019-10-23 06:04 UTC, n0str approved these changes

2019-10-23 09:21 UTC, neSpecc requested changes

2019-10-23 09:21 UTC, neSpecc commented on messages.py
> +    'Hot-Tsundere eto zlo'
непонятное сообщение

2019-10-30 19:25 UTC, n0str requested changes

2019-10-30 19:25 UTC, n0str commented on manager_ai/core/messages/message_creator.py
> +""" A function that creates new notification using user-config
Docstrings должны соответствовать стандарту https://www.python.org/dev/peps/pep-0257/

2019-10-30 19:25 UTC, n0str commented on tests/message_creator_test.py
> +        print(create_message(user_conf))
Вместо print должны быть assert'ы, чтобы с ними сравнивать.
https://docs.python.org/3/library/unittest.html#assert-methods

2019-10-30 20:57 UTC, neSpecc requested changes

2019-10-30 20:57 UTC, neSpecc commented on manager_ai/core/messages/message_templates.py
> +    'Надо что-нибудь опубликовать в канале',
Сообщения не должны быть захардкожены в репозиторий.

2019-11-06 15:01 UTC, n0str approved these changes

2019-12-06 17:57 UTC, closed without merging